language: python
python:
  - 2.7_with_system_site_packages
  - 3.6

before_install: sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install -r requirements.txt
  - pip install pylama pytest pytest-cov

before_script: pylama -i E501,E111,E127,E128,E402,E303 src/ || true
script: python -m pytest --cov=src/ src/luminol/tests/
